name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_push_image:
      name: Build and Push Image
      uses: zooniverse/ci-cd/.github/workflows/build_and_push_image.yaml@main
      with:
        repo_name: email-verify
        commit_id: ${{ github.sha }}

  deploy_production:
    needs: build_and_push_image
    name: Deploy to Production
    uses: zooniverse/ci-cd/.github/workflows/deploy_app.yaml@main
    with:
      app_name: email-verify
      repo_name: email-verify
      commit_id: ${{ github.sha }}
      environment: production
      deploy_check: false
    secrets:
      creds: ${{ secrets.AZURE_AKS }}

  slack_notification:
    name: Send Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy_production
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Deploy to Production / deploy_production
      status: ${{ needs.deploy_production.result }}
      # Customize the slack message
      title: 'Email verify deploy complete'
      title_link: 'ses-bounces.zooniverse.org'
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
