name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_push_image:
      name: Build and Push Image
      uses: zooniverse/ci-cd/.github/workflows/build_and_push_image.yaml@main
      with:
        repo_name: email-verify
        commit_id: ${{ github.sha }}

  deploy_production:
    name: Deploy to Production
    uses: zooniverse/ci-cd/.github/workflows/deploy_app.yaml@main
    with:
      app_name: email-verify
      repo_name: email-verify
      commit_id: ${{ github.sha }}
      environment: production
      deploy_check: false
    secrets:
      creds: ${{ secrets.AZURE_AKS }}
